#ifndef PROJECT_CRITERIA_SQUARE_SELECTOR_CONFIG_HPP_
#define PROJECT_CRITERIA_SQUARE_SELECTOR_CONFIG_HPP_

const int MEDIAN_BLUR_PARAM = 5;
const int THRESHOLD_PARAM = 100;
const int MAX_THRESHOLD_PARAM = 255;
const double APPROX_POLY_DP_EPSILON_MULTIPLIER = 0.02;

const double MIN_SIDES_RATIO = 0.85;
const double MAX_SIDES_RATIO = 1.15;

const double EPSILON = 1e-10;

const double MIN_ANGLES_DEGREE = 80.0;
const double MAX_ANGLES_DEGREE = 100.0;

const double MIN_AREA = 1000.0;

#endif  // ROJECT_CRITERIA_SQUARE_SELECTOR_CONFIG_HPP
